// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnqdgbwgsbyesfhvncmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucWRnYndnc2J5ZXNmaHZuY21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NTI3ODAsImV4cCI6MjA4ODEyODc4MH0.YVkbrOV_8Wsbu0l98nMbtzu2SxanIS0RFMGQg_fcGUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});